services:

  development-environment:
    build: 
      context: 
        .
      target: 
        development-environment
    restart: 
      unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
