name: Test On Push

on:
  push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --target test-project --tag test-project .

      - name: Run tests
        run: docker run --rm test-project
