name: Test On Push

on:
  push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd test_project

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run tests
        run: docker run --rm myapp
